CREATE TABLE Pro(id INT,name1 VARCHAR(10),email VARCHAR(20),created_at VARCHAR(10),updated_at VARCHAR(10),status1 VARCHAR(20),description1 VARCHAR(20),price BIGINT,quantity float,category VARCHAR(10));
USE Assignment;
DROP TABLE pro;
ALTER TABLE Product ADD COLUMN Buy VARCHAR(10);
ALTER TABLE Product ADD COLUMN Import VARCHAR(10);
ALTER TABLE Product ADD COLUMN remove VARCHAR(10);
ALTER TABLE Product ADD COLUMN Export VARCHAR(10);
ALTER TABLE Product DROP COLUMN Export ;
ALTER TABLE Product RENAME COLUMN remove to exitfrom;
ALTER TABLE Product RENAME COLUMN Import to importto;
ALTER TABLE Product RENAME COLUMN name to names;
ALTER TABLE Product RENAME COLUMN updated_at to Info;
ALTER TABLE product MODIFY names VARCHAR(200);
ALTER TABLE product MODIFY email VARCHAR(200);
ALTER TABLE product MODIFY quantity BIGINT;
ALTER TABLE product MODIFY category VARCHAR(50);

CREATE TABLE customers(customer_id INT,first_name VARCHAR(10),last_name CHAR(2),email VARCHAR(10),phone_number BIGINT,address VARCHAR(20),city VARCHAR(20),zip_code VARCHAR(20),country CHAR,created_at VARCHAR(10));
ALTER TABLE customers ADD COLUMN Buy VARCHAR(10);
ALTER TABLE customers ADD COLUMN Import VARCHAR(10);
ALTER TABLE customers ADD COLUMN remove VARCHAR(10);
ALTER TABLE customers ADD COLUMN Export VARCHAR(10);
ALTER TABLE customers DROP COLUMN Export ;
ALTER TABLE customers RENAME COLUMN remove to customize;
ALTER TABLE customers RENAME COLUMN Import to Sell;
ALTER TABLE customers RENAME COLUMN Export to recive;
ALTER TABLE customers RENAME COLUMN updated_at to Info;
ALTER TABLE customers MODIFY first_name VARCHAR(200);
ALTER TABLE customers MODIFY last_name varchar(5);
ALTER TABLE customers MODIFY address VARCHAR(200);
ALTER TABLE customers MODIFY country VARCHAR(10);

CREATE TABLE accounts(account_id INT, user_id INT, account_type VARCHAR(20), account_number VARCHAR(30), balance BIGINT, currency VARCHAR(10), status VARCHAR(20), opened_at VARCHAR(20), last_transaction_at VARCHAR(20), is_active BOOLEAN);
ALTER TABLE accounts ADD COLUMN Pay BIGINT;
ALTER TABLE accounts ADD COLUMN Withdraw BIGINT;
ALTER TABLE accounts ADD COLUMN Deposit BIGINT;
ALTER TABLE accounts ADD COLUMN Rent BIGINT;
ALTER TABLE accounts DROP COLUMN Rent ;
ALTER TABLE accounts RENAME COLUMN status to Info;
ALTER TABLE accounts RENAME COLUMN Pay to Payment;
ALTER TABLE accounts RENAME COLUMN account_id to acc_id;
ALTER TABLE accounts RENAME COLUMN account_type to acc_type;
ALTER TABLE accounts MODIFY account_type VARCHAR(200);
ALTER TABLE accounts MODIFY account_number varchar(11);
ALTER TABLE accounts MODIFY Info VARCHAR(200);
ALTER TABLE accounts MODIFY currency VARCHAR(150);

CREATE TABLE registrations(registration_id INT, user_id INT, event_id INT, registration_date VARCHAR(20), status VARCHAR(20), payment_status VARCHAR(20), payment_method VARCHAR(20), transaction_id VARCHAR(30), remarks VARCHAR(50), created_at VARCHAR(20));
ALTER TABLE registrations ADD COLUMN Open varchar(10);
ALTER TABLE registrations ADD COLUMN Close varchar(10);
ALTER TABLE registrations ADD COLUMN Transfer varchar(10);
ALTER TABLE registrations ADD COLUMN Details varchar(10);
ALTER TABLE registrations DROP COLUMN Details ;
ALTER TABLE registrations RENAME COLUMN Open to Open_acc;
ALTER TABLE registrations RENAME COLUMN Close to Close_acc;
ALTER TABLE registrations RENAME COLUMN Transfer to Transfer_acc;
ALTER TABLE registrations RENAME COLUMN remarks to remark;
ALTER TABLE registrations MODIFY status VARCHAR(200);
ALTER TABLE registrations MODIFY payment_status varchar(200);
ALTER TABLE registrations MODIFY event_id bigint;
ALTER TABLE registrations MODIFY payment_status VARCHAR(50);

CREATE TABLE employees(emp_id INT, first_name VARCHAR(50), last_name VARCHAR(50), email VARCHAR(100), phone_number VARCHAR(20), hire_date VARCHAR(20), job_title VARCHAR(50), department VARCHAR(50), salary BIGINT, manager_id INT);
ALTER TABLE employees ADD COLUMN status varchar(20);
ALTER TABLE employees ADD COLUMN employmenttype VARCHAR(20);
ALTER TABLE employees ADD COLUMN dateofbirth VARCHAR(20);
ALTER TABLE employees ADD COLUMN gender VARCHAR(10);
ALTER TABLE employees DROP COLUMN manager_id ;
ALTER TABLE employees RENAME COLUMN employmenttype to employment_type;
ALTER TABLE employees RENAME COLUMN dateofbirth to date_of_birth;
ALTER TABLE employees RENAME COLUMN status to Detail;
ALTER TABLE employees RENAME COLUMN emp_id to Employe_id;
ALTER TABLE employees MODIFY last_name VARCHAR(10);
ALTER TABLE employees MODIFY email varchar(20);
ALTER TABLE employees MODIFY phone_number varchar(10);
ALTER TABLE employees MODIFY job_title VARCHAR(200);

SELECT * FROM Product;
SELECT * FROM accounts;
SELECT * FROM employees;
SELECT * FROM customers;
SELECT * FROM registrations;
